### ISSUE TITLE
manifest google is not being permamently

### ISSUE THREAD

**Issue by alpgulmez** [ZazerConer/YouTube-to-M3U8#3]
Hello im getting m3u8 in source page. im writing m3u8 in search bar and im finding. but i have problems. ist not being permamently. its closing and i need changing new link for resume to watch how can i fix it.

**Comment by ZazerConer** [comment]
> Hello im getting m3u8 in source page. im writing m3u8 in search bar and im finding. but i have problems. ist not being permamently. its closing and i need changing new link for resume to watch how can i fix it.

Sorry, not clear what you are saying but I understand a bit of your problem. 

Do you mean m3u8, is this link?
`https://manifest.googlevideo.com/` 

If so, I will explain about the explanation. 

1. "manifest.google" is not a permalink. It is automatically generated from the m3u8 link you got from that source and is just a temporary link. This link has a fixed duration at all times as long as you do not exit the video you are watching. But when you close or don't watch a video from a link you used before, in a few minutes the link won't work anymore and it won't be useful to play the video again. 

Example link `expire`:

`https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1688940886/...`

So, to fix this problem, you need to use the origin m3u8 link source to play the video without changing the new url link. 

This is the link you should use: 

`https://raw.githubusercontent.com/username/YouTube-to-M3U8/main/channel-name.m3u8`

2. If you create a youtube channel url code you need to get the actual URL. 

YouTube channel URL. 

e.g: `https://www.google.com/@mytube/live` 

The above URL can be `Custom URL`, `Legacy Username URL` and `YouTube Handle URL`. 
For better understanding see here: https://github.com/ZazerConer/liveYTmalaysia/blob/main/README.md#add-youtube-live-url-with-m3u8-link 

Some youtube channels usually use their channel name for the direct youtube url and the link on the video may change or stop temporarily. So, I recommend you to use youtube channel ID to get youtube live channel URL because it is more complete and comprehensive like channel name, channel url and channel link. 

YouTube channel URL with `ID`. 

e.g: `https://www.youtube.com/channel/UCzDknC7OXxAZkeEsgugjU2w/live` 

To get youtube channel ID go here: https://commentpicker.com/youtube-channel-id.php 

And that's it! 

I hope you understand this explanation and can help you. If I'm wrong, please explain your problem in more detail so I can solve your problem.
